// Older releases seeded these exact IDs in browser storage. Keep user-created records.
function browserRecords(key,seedIds){const records=load(key,[]);if(!Array.isArray(records))return[];const kept=records.filter(record=>!seedIds.includes(record.id));if(kept.length!==records.length){try{save(key,kept)}catch{}}return kept}
const state = {
  view:viewFromHash(),
  entries:browserRecords("atlas.entries",["e1","e2","e3","e4"]), runs:browserRecords("atlas.runs",["r1","r2","r3"]),
  endpoint:load("atlas.endpoint","")||(location.port==="8088"?location.origin:""), connected:false, health:null, signals:null,
  query:"", filter:"All entries", mediaJobs:[], impacts:[], uploading:null
};
const titles = {
  overview:["Research overview","Your active work, systems, and signals in one place."],
  knowledge:["Knowledge index","Search papers, notes, and experiment logs together."],
  experiments:["Experiment registry","Track reproducible runs and compare outcomes."],
  signals:["System signals","Inspect measured runtime traffic, latency, and resource use."],
  media:["Media pipeline","Prepare demos and research artifacts for sharing."],
  docs:["Live docs","Write together, with agents that suggest instead of overwrite."]
};

// A hash can carry a second segment, as in #docs/<id>. The first names the view.
function viewFromHash(){return (location.hash||"#overview").slice(1).split("/")[0]}

function load(key,fallback){try{const value=localStorage.getItem(key);return value?JSON.parse(value):fallback}catch{return fallback}}
function save(key,value){localStorage.setItem(key,JSON.stringify(value))}
function escapeHTML(value=""){return String(value).replace(/[&<>'"]/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;","'":"&#39;",'"':"&quot;"}[char]))}
function relative(value){if(!value)return "—";const seconds=Math.max(0,(Date.now()-new Date(value).getTime())/1000);if(seconds<60)return "Now";if(seconds<3600)return `${Math.floor(seconds/60)}m`;if(seconds<86400)return `${Math.floor(seconds/3600)}h`;return `${Math.floor(seconds/86400)}d`}
function api(path,options={}){return fetch(`${state.endpoint}${path}`,{...options,headers:{"Content-Type":"application/json",...(options.headers||{})}}).then(async response=>{if(!response.ok)throw new Error((await response.text())||response.statusText);return response.status===204?null:response.json()})}
function modeLabel(){return state.connected?"Connected runtime":"Browser mode"}
function heading(actions="",includeEntry=true){const [title,copy]=titles[state.view]||titles.overview;return `<section class="page-heading"><div><p class="eyebrow">${state.connected?"Live workspace":"Private browser workspace"}</p><h1>${title}</h1><p>${copy}</p></div><div class="heading-actions">${actions}${includeEntry?`<button class="button primary" data-action="new-entry">＋ New entry</button>`:""}</div></section>`}

function browserMode(){state.connected=false;state.health=null;state.signals=null;state.entries=browserRecords("atlas.entries",["e1","e2","e3","e4"]);state.runs=browserRecords("atlas.runs",["r1","r2","r3"]);state.mediaJobs=[];state.impacts=[];renderRuntime();render()}
async function refreshRuntime(){
  const [health,entries,runs,signals,jobs,impacts]=await Promise.all([api("/api/health"),api("/api/entries"),api("/api/runs"),api("/api/signals"),api("/api/video/v1/jobs"),api("/api/impact-experiments")]);
  state.health=health;state.entries=entries.entries||[];state.runs=runs.runs||[];state.signals=signals;state.mediaJobs=jobs.jobs||[];
  state.impacts=impacts.impact_experiments||[];
  state.connected=true;renderRuntime();render();
}
async function refreshLiveData(){
  if(!state.connected)return;
  try{
    const [health,signals,jobs,impacts]=await Promise.all([api("/api/health"),api("/api/signals"),api("/api/video/v1/jobs"),api("/api/impact-experiments")]);
    state.health=health;state.signals=signals;state.mediaJobs=jobs.jobs||[];
    state.impacts=impacts.impact_experiments||[];
    if(["overview","signals","media","experiments"].includes(state.view))render();
  }catch(error){browserMode();toast(`Runtime unavailable: ${error.message}`)}
}
async function connect(){
  if(!state.endpoint){browserMode();return}
  try{
    await refreshRuntime();
  }catch(error){browserMode();toast(`Runtime unavailable: ${error.message}`)}
}
function renderRuntime(){
  const button=document.querySelector("#runtimeButton");
  button.innerHTML=`<i class="status-dot ${state.connected?"live":""}"></i><span><strong>${modeLabel()}</strong><small>${state.connected?escapeHTML(state.endpoint.replace(/^https?:\/\//,"")):"Stored on this device"}</small></span><span>›</span>`;
  document.querySelector("#systemState").innerHTML=`<i class="status-dot ${state.connected?"live":""}"></i>${state.connected?"Runtime connected":"No live runtime"}`;
}
function render(){
  // The docs view keeps its editor alive across renders and needs to know where the keyboard was.
  AtlasDocs.capture();
  document.querySelectorAll(".nav-item").forEach(button=>button.classList.toggle("active",button.dataset.view===state.view));
  const views={overview:overviewView,knowledge:knowledgeView,experiments:experimentsView,signals:signalsView,media:mediaView,docs:AtlasDocs.view};
  document.querySelector("#workspace").innerHTML=(views[state.view]||overviewView)();
  bindView();
  // Leaving the docs view closes the live connection to the open document.
  if(state.view==="docs")AtlasDocs.bind();else AtlasDocs.leave();
}
function overviewView(){
  const activeRuns=state.runs.filter(run=>run.status==="Running"||run.status==="Queued");
  const running=state.runs.filter(run=>run.status==="Running").length+state.impacts.filter(item=>item.experiment.status==="running").length;
  const p95=state.connected&&state.signals?.search_samples?`${(state.signals.search_p95_microseconds/1000).toFixed(2)} ms`:"—";
  return heading()+`<section class="metric-grid">
    ${metric(state.connected?"Indexed knowledge":"Saved knowledge",state.connected?state.health?.documents||0:state.entries.length,state.connected?"Searchable documents":"On this device","violet")}
    ${metric("Active experiments",running,`${state.runs.length} runs · ${state.impacts.length} impact`,"cyan")}
    ${metric("Search p95",p95,state.connected?`${state.signals?.search_samples||0} recent queries`:"Connect a runtime","amber")}
    ${metric("Runtime requests",state.connected?state.signals?.requests||0:"—",state.connected?"Since startup":"Connect a runtime","green")}
  </section><section class="dashboard-grid">
    <article class="panel chart-panel"><div class="panel-head"><div><p>Runtime traffic</p><h2>HTTP requests per minute</h2></div><span>${state.connected?"Including console checks · last 12 min":"No runtime"}</span></div>${trafficChart()}</article>
    <article class="panel systems-panel"><div class="panel-head"><div><p>Runtime inventory</p><h2>Core systems</h2></div><button data-view-link="signals">Inspect ›</button></div>${systems()}</article>
    <article class="panel recent-panel"><div class="panel-head"><div><p>Workspace</p><h2>Recently indexed</h2></div><button data-view-link="knowledge">View all ›</button></div>${state.entries.slice(0,3).map(entry=>entryRow(entry)).join("")||empty("No entries indexed")}</article>
    <article class="panel run-panel"><div class="panel-head"><div><p>Experiments</p><h2>Active runs</h2></div><button data-view-link="experiments">Registry ›</button></div>${activeRuns.slice(0,3).map(run=>`<div class="compact-row"><i class="run-dot ${escapeHTML(run.status.toLowerCase())}"></i><span><strong>${escapeHTML(run.name)}</strong><small>${escapeHTML(run.model)} · ${escapeHTML(run.dataset)}</small></span><em>${relative(run.updated_at)}</em></div>`).join("")||empty("No active runs")}</article>
  </section>`;
}
function metric(label,value,copy,color){return `<article class="metric-card"><div class="metric-symbol ${color}">◇</div><p>${label}</p><strong>${value}</strong><small>${copy}</small></article>`}
function trafficChart(){if(!state.connected)return empty("Connect an Atlas runtime to see measured traffic");const history=state.signals?.request_history||[];if(!history.length)return empty("No traffic recorded yet");const peak=Math.max(1,...history.map(bucket=>bucket.count));return `<div class="chart" aria-label="Requests per minute">${history.map(bucket=>`<i style="height:${bucket.count?Math.max(3,bucket.count/peak*100):0}%" title="${bucket.count} requests"></i>`).join("")}</div><div class="axis"><span>11 min ago</span><span>6 min ago</span><span>Now</span></div>`}
function systems(){if(!state.connected)return empty("Connect an Atlas runtime to inspect its services");const data=[{name:"Knowledge",detail:`${state.health?.documents||0} searchable documents`},{name:"Experiments",detail:`${state.health?.runs||0} runs · ${state.health?.impact_experiments||0} impact experiments`},{name:"Live docs",detail:`${state.health?.docs||0} collaborative documents`},{name:"Signals",detail:`${state.health?.metric_series||0} durable metric series`}];return data.map(item=>`<div class="system-row"><span class="system-icon">▧</span><div><strong>${item.name}</strong><small>${item.detail}</small></div></div>`).join("")}
function entryRow(entry){return `<button class="entry-row" data-view-link="knowledge"><span class="type ${escapeHTML(entry.type.toLowerCase().replace(" ","-"))}">${escapeHTML(entry.type[0])}</span><span><strong>${escapeHTML(entry.title)}</strong><small>${escapeHTML(entry.type)} · ${relative(entry.updated_at)}</small></span><b>›</b></button>`}

function applyFilter(entries){const singular={Papers:"Paper",Notes:"Note","Run logs":"Run log"}[state.filter];return singular?entries.filter(entry=>entry.type===singular):entries}
function localSearch(query){const words=query.toLowerCase().split(/\s+/).filter(Boolean);if(!words.length)return applyFilter(state.entries);return applyFilter(state.entries.map(entry=>{const title=entry.title.toLowerCase(),text=`${entry.title} ${entry.body} ${(entry.tags||[]).join(" ")}`.toLowerCase();return{entry,score:words.reduce((sum,word)=>sum+(title.includes(word)?3:0)+(text.includes(word)?1:0),0)}}).filter(item=>item.score).sort((a,b)=>b.score-a.score).map(item=>item.entry))}
function knowledgeView(){const results=localSearch(state.query);return heading()+`<section class="panel knowledge-panel"><div class="large-search"><span>⌕</span><input id="knowledgeSearch" value="${escapeHTML(state.query)}" placeholder="Search by idea, method, tag, or result"><em>${results.length} matches</em></div><div class="filters">${["All entries","Papers","Notes","Run logs"].map(filter=>`<button class="${filter===state.filter?"active":""}" data-filter="${filter}">${filter}</button>`).join("")}</div><div id="searchResults" class="results">${resultHTML(results)}</div></section>`}
function resultHTML(results){return results.map(entry=>`<article><span class="type ${escapeHTML(entry.type.toLowerCase().replace(" ","-"))}">${escapeHTML(entry.type[0])}</span><div><div class="result-meta"><span>${escapeHTML(entry.type)}</span><span>${relative(entry.updated_at)}</span></div><h2>${entry.type==="Doc"?`<a href="#docs/${escapeHTML(entry.id.replace(/^doc:/,""))}">${escapeHTML(entry.title)}</a>`:escapeHTML(entry.title)}</h2><p>${escapeHTML(entry.body)}</p><div class="tags">${(entry.tags||[]).map(tag=>`<span>${escapeHTML(tag)}</span>`).join("")}</div></div></article>`).join("")||empty("No indexed entry matches your search")}

function pct(value){return `${(Number(value||0)*100).toFixed(2)}%`}
function historyChart(result){const points=result.history||[];if(points.length<2)return `<div class="impact-history empty-history">Convergence appears after 256 accepted events.</div>`;const lifts=points.map(point=>point.absolute_lift);const low=Math.min(0,...lifts),high=Math.max(0.001,...lifts),span=high-low;const line=points.map((point,index)=>`${index/(points.length-1)*100},${44-(point.absolute_lift-low)/span*40}`).join(" ");return `<svg class="impact-history" viewBox="0 0 100 48" preserveAspectRatio="none" role="img" aria-label="Estimated lift convergence over event time"><line x1="0" y1="${44-(0-low)/span*40}" x2="100" y2="${44-(0-low)/span*40}"></line><polyline points="${line}"></polyline></svg>`}
function impactCard(item){const experiment=item.experiment,result=item.result,relativeLift=result.relative_lift==null?"—":pct(result.relative_lift),ci=`${pct(result.confidence_low)} to ${pct(result.confidence_high)}`,lag=Math.round(result.diagnostics.processing_lag_p95_ms||0),stateKB=Math.ceil((result.diagnostics.state_bytes_estimate||0)/1024);return `<article class="panel impact-card"><div class="impact-head"><div><p class="eyebrow">Impact experiment · ${escapeHTML(experiment.status)}</p><h2>${escapeHTML(experiment.name)}</h2><p>${escapeHTML(experiment.hypothesis)}</p></div><i class="chip ${escapeHTML(experiment.status)}">${escapeHTML(experiment.status)}</i></div><div class="impact-metrics"><span><small>Absolute lift</small><strong>${pct(result.absolute_lift)}</strong></span><span><small>Relative lift</small><strong>${relativeLift}</strong></span><span><small>95% CI</small><strong>${ci}</strong></span><span><small>Sample</small><strong>${result.treatment_sample_size+result.control_sample_size}</strong></span></div>${historyChart(result)}<div class="impact-quality"><span>Treatment ${result.treatment_conversions}/${result.treatment_sample_size} · Control ${result.control_conversions}/${result.control_sample_size}</span><span>${result.insufficient_data?"Insufficient data · ":""}${escapeHTML(result.recommendation)}</span><span>${result.diagnostics.duplicates} duplicates · ${result.diagnostics.late} late · ${result.diagnostics.unmatched_outcomes} unmatched</span><span>p95 lag ${lag} ms · state ≈ ${stateKB} KiB</span></div><div class="impact-actions">${experiment.status==="draft"?`<button class="button primary" data-impact-start="${experiment.id}">Start</button>`:""}${experiment.status==="running"?`<button class="button secondary" data-impact-demo="${experiment.id}">Run synthetic ad demo</button><button class="button ghost" data-impact-stop="${experiment.id}">Complete & index conclusion</button>`:""}${experiment.analysis_doc_id?`<a class="button ghost" href="#docs/${escapeHTML(experiment.analysis_doc_id)}">Open analysis doc</a>`:""}</div></article>`}
function experimentsView(){const actions=`<button class="button secondary" data-action="new-run">◇ Register run</button>${state.connected?`<button class="button primary" data-action="new-impact">＋ Impact experiment</button>`:""}`;const impactSection=state.connected?`<section class="impact-section"><div class="section-head"><div><p class="eyebrow">Treatment versus control</p><h2>Impact experiments</h2></div><span>${state.impacts.length} experiments</span></div><div class="impact-list">${state.impacts.map(impactCard).join("")||empty("No impact experiments yet. Create one to measure causal lift.")}</div></section>`:`<section class="panel impact-connect"><h2>Impact experiments need a connected runtime</h2><p>Connect Atlas for durable assignment, event-time attribution, recovery, and shared results.</p><button class="button primary" data-action="connect-runtime">Connect a runtime</button></section>`;return heading(actions,false)+impactSection+`<section class="run-section"><div class="section-head"><div><p class="eyebrow">Simple tracking</p><h2>Experiment runs</h2></div><span>${state.runs.length} runs</span></div><section class="panel table-panel"><div class="table-toolbar"><span>${state.connected?"Records on the connected runtime":"Records stored on this device"}</span><em>Run registry</em></div><div class="run-table"><div class="table-row header"><span>Run</span><span>Model</span><span>Dataset</span><span>Status</span><span>Score</span><span>Updated</span></div>${state.runs.map(run=>`<div class="table-row"><span><strong>${escapeHTML(run.name)}</strong><small>#${escapeHTML(run.id.slice(0,8))}</small></span><span>${escapeHTML(run.model||"Not set")}</span><span>${escapeHTML(run.dataset||"Not set")}</span><span><i class="chip ${escapeHTML(run.status.toLowerCase())}">${escapeHTML(run.status)}</i></span><span>${typeof run.score==="number"?run.score.toFixed(3):"—"}</span><span>${relative(run.updated_at)}</span></div>`).join("")}</div>${state.runs.length?"":empty("No simple experiment runs recorded yet")}</section></section>`}
function signalsView(){if(!state.connected||!state.signals)return heading()+`<section class="panel">${empty("Connect an Atlas runtime to see measured signals")}</section>`;const signals=state.signals;const rows=[{name:"Search p95",value:signals.search_samples?(signals.search_p95_microseconds/1000).toFixed(2):"—",unit:signals.search_samples?"ms":"no queries"},{name:"Heap allocation",value:(signals.heap_bytes/1048576).toFixed(1),unit:"MB"},{name:"Goroutines",value:signals.goroutines,unit:"active"},{name:"Metric series",value:signals.metric_series,unit:"series"},{name:"Uptime",value:Math.floor(signals.uptime_seconds/60),unit:"min"}];return heading()+`<div class="signal-grid"><section class="panel latency-panel"><div class="panel-head"><div><p>Connected runtime</p><h2>Operational signals</h2></div><span class="live-badge"><i></i>Live</span></div>${rows.map(row=>`<div class="signal-row"><span>${row.name}</span><strong>${row.value} ${row.unit}</strong></div>`).join("")}</section><section class="panel"><div class="panel-head"><div><p>Measured activity</p><h2>Runtime counts</h2></div></div><div class="signal-row"><span>HTTP requests since startup</span><strong>${signals.requests}</strong></div><div class="signal-row"><span>Recent search samples</span><strong>${signals.search_samples}</strong></div><div class="signal-row"><span>Indexed documents</span><strong>${state.health?.documents||0}</strong></div><div class="signal-row"><span>Media jobs</span><strong>${state.health?.media_jobs||0}</strong></div></section></div>`}
function mediaView(){return heading()+`<div class="media-grid">${state.connected?`<label class="upload-zone"><input id="mediaFile" type="file" accept="video/*"><span class="upload-icon">⇧</span><h2>Prepare a research video</h2><p>Upload a recording for resumable processing into HLS renditions.</p><span class="button secondary">Choose video</span><small>The file uploads in 1 MB chunks to the connected runtime.</small></label>`:`<section class="panel upload-zone"><span class="upload-icon">⇧</span><h2>Media processing needs a runtime</h2><p>Connect Atlas to upload a real file and track its processing job.</p><button class="button primary" data-action="connect-runtime">Connect a runtime</button></section>`}<section class="panel"><div class="panel-head"><div><p>Pipeline</p><h2>Recent jobs</h2></div></div><div id="mediaJobs">${mediaJobsHTML()}</div></section></div>`}
function mediaJobsHTML(){return [...(state.uploading?[state.uploading]:[]),...state.mediaJobs].map(job=>{const name=job.name||job.id;const size=job.size_bytes?`${(job.size_bytes/1048576).toFixed(1)} MB · `:"";const status=job.state||job.status;const progress=job.progress;return `<div class="media-job"><span class="media-thumb">▷</span><div><strong>${escapeHTML(name)}</strong><small>${size}${escapeHTML(status)}${job.last_error?` · ${escapeHTML(job.last_error)}`:""}</small>${typeof progress==="number"?`<div class="progress"><i style="width:${progress}%"></i></div>`:""}</div><em>${typeof progress==="number"?`${progress}%`:escapeHTML(status)}</em></div>`}).join("")||empty(state.connected?"No media jobs have been queued":"Connect a runtime to see media jobs")}
function empty(text){return `<div class="empty">${escapeHTML(text)}</div>`}

function bindView(){
  document.querySelectorAll("[data-view-link]").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.viewLink)));
  document.querySelectorAll("[data-action='new-entry']").forEach(button=>button.addEventListener("click",entryModal));
  document.querySelectorAll("[data-action='new-run']").forEach(button=>button.addEventListener("click",runModal));
  document.querySelectorAll("[data-action='new-impact']").forEach(button=>button.addEventListener("click",impactModal));
  document.querySelectorAll("[data-action='connect-runtime']").forEach(button=>button.addEventListener("click",connectionModal));
  const search=document.querySelector("#knowledgeSearch");if(search)search.addEventListener("input",async event=>{state.query=event.target.value;let results=localSearch(state.query);if(state.connected&&state.query.trim()){try{const data=await api(`/api/search?q=${encodeURIComponent(state.query)}&limit=30`);results=data.results.map(item=>item.entry)}catch{}}document.querySelector("#searchResults").innerHTML=resultHTML(results)});
  document.querySelectorAll("[data-filter]").forEach(button=>button.addEventListener("click",()=>{state.filter=button.dataset.filter;render()}));
  const file=document.querySelector("#mediaFile");if(file)file.addEventListener("change",event=>event.target.files[0]&&uploadMedia(event.target.files[0]));
  document.querySelectorAll("[data-impact-start]").forEach(button=>button.addEventListener("click",()=>impactAction(button.dataset.impactStart,"start")));
  document.querySelectorAll("[data-impact-stop]").forEach(button=>button.addEventListener("click",()=>impactAction(button.dataset.impactStop,"stop")));
  document.querySelectorAll("[data-impact-demo]").forEach(button=>button.addEventListener("click",()=>runImpactDemo(button.dataset.impactDemo)));
}
function setView(view){state.view=view;location.hash=view;render()}
function modal(content){document.querySelector("#modalRoot").innerHTML=`<div class="modal-backdrop"><section class="modal">${content}</section></div>`;document.querySelector(".modal-backdrop").addEventListener("mousedown",event=>event.target===event.currentTarget&&closeModal());document.querySelectorAll("[data-close]").forEach(button=>button.addEventListener("click",closeModal))}
function closeModal(){document.querySelector("#modalRoot").innerHTML=""}
function entryModal(){modal(`<button class="modal-close" data-close>×</button><p class="modal-kicker">Atlas workspace</p><h2>Index a new entry</h2><p class="modal-copy">Add material you want to retrieve alongside papers and experiment logs.</p><form id="entryForm" class="form"><label>Title<input name="title" autofocus required placeholder="Evaluation protocol notes"></label><label>Type<select name="type"><option>Note</option><option>Paper</option><option>Run log</option></select></label><label>Content<textarea name="body" rows="4" placeholder="Key ideas, findings, or decisions"></textarea></label><label>Tags<input name="tags" placeholder="evaluation, retrieval, benchmark"></label><div class="form-actions"><button type="button" class="button ghost" data-close>Cancel</button><button class="button primary">Index entry</button></div></form>`);document.querySelector("#entryForm").addEventListener("submit",saveEntry);document.querySelector("#entryForm input").focus()}
async function saveEntry(event){event.preventDefault();const data=new FormData(event.target);let entry={title:data.get("title").trim(),type:data.get("type"),body:data.get("body").trim(),tags:data.get("tags").split(",").map(tag=>tag.trim()).filter(Boolean)};try{if(state.connected){entry=(await api("/api/entries",{method:"POST",body:JSON.stringify(entry)})).entry;if(state.health){state.health.entries++;state.health.documents++}}else{entry={...entry,id:crypto.randomUUID(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()};save("atlas.entries",[entry,...state.entries])}state.entries.unshift(entry);closeModal();render();toast(state.connected?"Entry persisted and indexed":"Entry saved on this device")}catch(error){toast(error.message)}}
function runModal(){modal(`<button class="modal-close" data-close>×</button><p class="modal-kicker">Experiment registry</p><h2>Track a new run</h2><p class="modal-copy">Keep the model, dataset, status, score, and notes together for reproducibility.</p><form id="runForm" class="form"><label>Run name<input name="name" autofocus required placeholder="Retrieval sweep 018"></label><div class="form-split"><label>Model<input name="model" placeholder="BM25"></label><label>Dataset<input name="dataset" placeholder="wiki-100k"></label></div><label>Status<select name="status"><option>Running</option><option>Queued</option><option>Complete</option></select></label><label>Notes<textarea name="notes" rows="3" placeholder="Hypothesis or configuration"></textarea></label><div class="form-actions"><button type="button" class="button ghost" data-close>Cancel</button><button class="button primary">Create run</button></div></form>`);document.querySelector("#runForm").addEventListener("submit",saveRun);document.querySelector("#runForm input").focus()}
async function saveRun(event){event.preventDefault();const data=new FormData(event.target);let run={name:data.get("name").trim(),model:data.get("model").trim(),dataset:data.get("dataset").trim(),status:data.get("status"),notes:data.get("notes").trim()};try{if(state.connected){run=(await api("/api/runs",{method:"POST",body:JSON.stringify(run)})).run;if(state.health)state.health.runs++}else{run={...run,id:crypto.randomUUID(),created_at:new Date().toISOString(),updated_at:new Date().toISOString()};save("atlas.runs",[run,...state.runs])}state.runs.unshift(run);closeModal();render();toast("Experiment registered")}catch(error){toast(error.message)}}
function impactModal(){modal(`<button class="modal-close" data-close>×</button><p class="modal-kicker">Impact experiments</p><h2>Measure treatment lift</h2><p class="modal-copy">Define the outcome and holdout before assigning subjects. Synthetic identifiers only.</p><form id="impactForm" class="form"><label>Name<input name="name" autofocus required placeholder="Campaign conversion lift"></label><label>Hypothesis<textarea name="hypothesis" rows="2" required placeholder="The campaign causes conversions that would not otherwise occur."></textarea></label><div class="form-split"><label>Success outcome<input name="outcome" required value="conversion"></label><label>Treatment allocation<input name="allocation" type="number" min="0.01" max="0.99" step="0.01" value="0.50"></label></div><div class="form-split"><label>Observation window (hours)<input name="window" type="number" min="1" value="168"></label><label>Analysis live doc ID<input name="doc" placeholder="Optional"></label></div><div class="form-actions"><button type="button" class="button ghost" data-close>Cancel</button><button class="button primary">Create draft</button></div></form>`);document.querySelector("#impactForm").addEventListener("submit",saveImpact);document.querySelector("#impactForm input").focus()}
async function saveImpact(event){event.preventDefault();const data=new FormData(event.target);const config={name:data.get("name").trim(),hypothesis:data.get("hypothesis").trim(),outcome_name:data.get("outcome").trim(),treatment_allocation:Number(data.get("allocation")),observation_window_seconds:Number(data.get("window"))*3600,analysis_doc_id:data.get("doc").trim()};try{await api("/api/impact-experiments",{method:"POST",body:JSON.stringify(config)});closeModal();await refreshRuntime();toast("Impact experiment created as a draft")}catch(error){toast(error.message)}}
async function impactAction(id,action){try{await api(`/api/impact-experiments/${id}/${action}`,{method:"POST"});await refreshRuntime();toast(action==="start"?"Impact experiment started":"Conclusion indexed in Knowledge")}catch(error){toast(error.message)}}
async function runImpactDemo(id){toast("Generating synthetic assignments, impressions, clicks, delayed conversions, and duplicate deliveries…");try{await api(`/api/impact-experiments/${id}/demo`,{method:"POST",body:JSON.stringify({subjects:5000,control_rate:0.08,absolute_lift:0.04,duplicate_pct:0.03,seed:20261007})});await refreshRuntime();toast("Synthetic advertising demo complete")}catch(error){toast(error.message)}}
function connectionModal(){modal(`<button class="modal-close" data-close>×</button><p class="modal-kicker">Atlas runtime</p><h2>Connect your local service</h2><p class="modal-copy">Run <code>make atlas</code>, then enter its address for durable storage and real telemetry.</p><form id="connectionForm" class="form"><label>Atlas API URL<input name="endpoint" type="url" value="${escapeHTML(state.endpoint)}" placeholder="http://localhost:8088"></label><div class="connection-note"><strong>Browser mode remains available.</strong><span>Leave this blank to keep your workspace in browser storage.</span></div><div class="form-actions"><button type="button" class="button ghost" data-close>Cancel</button><button class="button primary">Save connection</button></div></form>`);document.querySelector("#connectionForm").addEventListener("submit",async event=>{event.preventDefault();state.endpoint=new FormData(event.target).get("endpoint").trim().replace(/\/$/,"");save("atlas.endpoint",state.endpoint);closeModal();await connect();render()})}
function commandModal(){modal(`<div class="command-input"><span>⌕</span><input id="commandSearch" autofocus placeholder="Go to a workspace"><kbd>ESC</kbd></div><p class="command-label">Navigate</p>${Object.keys(titles).map((view,index)=>`<button class="command-item" data-command-view="${view}"><span>${titles[view][0]}</span><kbd>${index+1}</kbd></button>`).join("")}`);document.querySelectorAll("[data-command-view]").forEach(button=>button.addEventListener("click",()=>{closeModal();setView(button.dataset.commandView)}));document.querySelector("#commandSearch").focus()}
async function uploadMedia(file){if(!state.connected)return;const job={name:file.name,status:"Uploading",progress:0,size_bytes:file.size};state.uploading=job;render();try{const created=await api("/api/video/v1/uploads",{method:"POST"});const id=created.upload_id;let offset=0;const chunkSize=1048576;while(offset<file.size){const chunk=file.slice(offset,offset+chunkSize);const response=await fetch(`${state.endpoint}/api/video/v1/uploads/${id}`,{method:"PATCH",headers:{"Upload-Offset":String(offset)},body:chunk});if(!response.ok)throw new Error(await response.text());offset=Number(response.headers.get("Upload-Offset"));job.progress=Math.round(offset/file.size*100);state.view==="media"&&render()}await api(`/api/video/v1/uploads/${id}/complete`,{method:"POST",headers:{"X-Upload-Name":encodeURIComponent(file.name)}});state.uploading=null;await refreshRuntime();toast("Video uploaded and processing job queued")}catch(error){job.status="Upload failed";render();toast(error.message)}}
function toast(message){const element=document.querySelector("#toast");element.textContent=message;element.classList.add("show");clearTimeout(toast.timer);toast.timer=setTimeout(()=>element.classList.remove("show"),2800)}

document.querySelectorAll(".nav-item").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.view)));
document.querySelectorAll(".secondary-link").forEach(button=>button.addEventListener("click",()=>setView(button.dataset.view)));
document.querySelector("#runtimeButton").addEventListener("click",connectionModal);
document.querySelector("#commandButton").addEventListener("click",commandModal);
window.addEventListener("hashchange",()=>{state.view=viewFromHash();render()});
window.addEventListener("keydown",event=>{if((event.metaKey||event.ctrlKey)&&event.key.toLowerCase()==="k"){event.preventDefault();commandModal()}if(event.key==="Escape")closeModal();if(!event.metaKey&&!event.ctrlKey&&!event.altKey&&/^[1-6]$/.test(event.key)&&!["INPUT","TEXTAREA","SELECT"].includes(document.activeElement?.tagName||""))setView(Object.keys(titles)[Number(event.key)-1])});
renderRuntime();render();connect();
setInterval(refreshLiveData,15000);
